In [2]:
import numpy as np 
import matplotlib.pyplot as plt 

In [3]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [18]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr)
arr.flatten()
np.expand_dims(arr, axis=0)


[1 2 3]


array([[1, 2, 3]])

In [6]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [7]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
np.expand_dims(arr, axis=0)

array([[1, 2, 3]])

In [21]:
np.random.rand(3,3)

array([[0.61552065, 0.06477925, 0.16472215],
       [0.43897402, 0.75800373, 0.73009964],
       [0.37754669, 0.34395755, 0.17814862]])

In [22]:
np.random.randint(0, 10, size=(2,2))

array([[7, 9],
       [3, 6]], dtype=int32)

In [23]:
np.random.randn(3,3)

array([[ 1.08317369,  0.10086173, -1.08561868],
       [ 0.3115257 ,  1.23552665,  0.54971179],
       [-1.01363127,  0.58568862, -2.28709611]])

In [24]:
np.mean(arr)

np.float64(2.0)

In [25]:
np.std(arr)

np.float64(0.816496580927726)

In [26]:
np.sum(arr)

np.int64(6)

In [27]:
np.max(arr)

np.int64(3)

In [28]:
np.min(arr)

np.int64(1)

In [29]:
np.argmax([0.1, 0.8, 0.1])

np.int64(1)

In [35]:
A=np.array([[1,2],[5,7]])
B=np.array([3,4])
np.dot(A, B)
A @ B


array([11, 43])

In [36]:
A.T

array([[1, 5],
       [2, 7]])

In [37]:
np.linalg.inv(A)

array([[-2.33333333,  0.66666667],
       [ 1.66666667, -0.33333333]])

In [38]:
np.linalg.eig(A)

EigResult(eigenvalues=array([-0.35889894,  8.35889894]), eigenvectors=array([[-0.82713818, -0.26226628],
       [ 0.5619986 , -0.96499554]]))

In [40]:
x=np.array([0,1,2])
np.maximum(0, x)

array([0, 1, 2])

In [41]:
1 / (1 + np.exp(-x))

array([0.5       , 0.73105858, 0.88079708])

NameError: name 'data' is not defined

In [42]:
exp_x = np.exp(x)

softmax = exp_x / np.sum(exp_x)